config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books, only:[:index, :show, :create, :edit, :destroy, :update]
  resources :users, only:[:index, :show, :create, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one_attached :profile_image


  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: {maximum: 200}


  def get_profile_image
    if profile_image.attached?
      profile_image.variant(resize_to_limit: [80,80])
    else
      'no_image.jpg'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, uniqueness: true
  validates :name, length: {minimum:2, maximum: 20}
  validates :introduction, length: {maximum: 50}

  def get_profile_image
    if profile_image.attached?
      profile_image.variant(resize_to_limit: [100,100])
    else
      'no_image.jpg'
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(current_user)
  end



  def after_sign_out_path_for(resource)
    root_path
  end

  protected



  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :correct_user, only: [:edit, :update]

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have updated user successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render "index"
    end
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @user = @books.user
  end

  def edit
    @book = Book.find(params[:id])
    @books = Book.new
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render "edit"
    end
  end

  private


  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

  def user_params
    params.require.(:user).permit(:name, :profile_image, :introduction)
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit]


  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def create
    @user = User.new(user_params)
    @user.user_id = current_user.id
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end


  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to user_path(current_user) unless @user == current_user
    end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>User info</h2>
  <table class="table">
    <tbody>
      <tr>
        <%= image_tag user.get_profile_image %>
      </tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
  </div>
  <h2>New book</h2>
    <%= form_with model: book do |f| %>
    <h4>Title</h4>
      <%= f.text_field :title %>

    <h4>Opinion</h4>
      <%= f.text_area :body %><br>
    <%= f.submit "Create Book", class: "btn btn-success" %>
    <% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
        <% if @book.errors.any? %>
          <%= @book.errors.count %>error prohibited this obj from being saved:
            <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
        <% end %>
        <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
        <div class="form-group">
          <label for="inputName">Title</label><br>
          <%= f.text_field :title, autofocus: true, id:"inputTitle"%>
        </div>
        <div class="form-group">
          <label for="user_introduction">Opinion</label><br>
          <%= f.text_area :body, autofocus: true %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
        <%= link_to "Show", book_path %>
        /
        <%= link_to "Back", books_path %>
        <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div id="error_explanation">
    <% if @book.errors.any? %>
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-3">
    <%= render 'list', user: @user, book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
       <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan=3></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= image_tag book.user.get_profile_image %>
              <% end %>
              </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'list', user: @user, book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
          <table class="table">
            <tbody>
              <tr>
                <th>
                  <%= image_tag @user.get_profile_image %><br>
                  <%= link_to @user.name, user_path(@user) %>
                </th>
                <th>
                  <%= link_to @books.title, book_path(@books) %>
                </th>
                <th>
                  <%= @books.body %>
                </th>
                <% if @books.user_id == current_user.id %>
                <th>
                  <%= link_to "Edit", edit_book_path(@books.id), class: "btn btn-sm btn-success" %>
                </th>
                <th>
                  <%= link_to "Destroy", book_path(@books.id), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に削除しますか？" %>
                </th>
                <% end %>
              </tr>
            </tbody>
          </table>
      </div>
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>
        Welcome to
        <i class="fas fa-book"></i><strong>Bookers</strong>!
      </h1>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to
        <i class="fas fa-book"></i><strong>Bookers</strong>
        !!
      </h1>
      <p>In
      <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can shere and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <script src="https://kit.fontawesome.com/127dcb1b69.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
       <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container">
            <a class="navbar-brand" href="/">
              <span>Bookers</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user), class: "nav-link text-light" do %>
                    <i class= "fas fa-home"></i>
                     Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: "nav-link text-light" do %>
                   <i class="fas fa-users"></i>
                     Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class: "nav-link text-light" do %>
                   <i class="fas fa-book-open"></i>
                     Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do  %>
                   <i class="fas fa-sign-out-alt"></i>
                     Log out
                  <% end %>
                </li>
                <% else %>
                <li>
                  <%= link_to root_path, class: "nav-link text-light" do %>
                   <i class= "fas fa-home"></i>
                     Home
                  <% end %>
                </li>
                <li>
                  <%= link_to home_about_path, class: "nav-link text-light" do %>
                   <i class="fas fa-link"></i>
                     About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                   <i class="fas fa-user-plus"></i>
                     Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                   <i class="fas fa-sign-in-alt"></i>
                     Log in
                  <% end %>
                </li>
                <% end %>
              </ul>
            </div>
          </div>
    </header>
      <p id="notice"></p>
      <%= flash[:notice] %>

    <%= yield %>

    <main>
    </main>


    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/undefined/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/undefined/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/_list.html.erb
<% if users.errors.any? %>
  <%= users.errors.count %>件のエラーが発生しました
  <ul>
    <% users.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h2>User info</h2>
  <table class="table">
    <tbody>
      <tr>
        <%= image_tag user.get_profile_image %>
      </tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fa-solid fa-users-gear"></i>
      <% end %>
  </div>
  <h2>New Book</h2>
      <%#仮コード%>
    <%= form_with model: book do |f| %>
    <h4>Title</h4>
      <%= f.text_field :title %>

    <h4>Opinion</h4>
      <%= f.text_area :body %><br>
    <%= f.submit "Create Book", class: "btn btn-success" %>
    <% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
        <div id="error_explanation">
          <% if @user.errors.any? %>
            <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
              <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
          <% end %>
        </div>
      <%= form_with model: @user, url: user_path(@user.id), method: :patch do |f| %>
      <div class="form-group">
        <label for="inputName">Name</label><br>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"name"%>
      </div>
      <div class="form-group">
        <label for="inputImage">Image</label><br>
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
      </div>
      <div class="form-group">
        <label for="user_introduction">Introduction</label><br>
        <%= f.text_area :introduction, autofocus: true, placeholder: "introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update User", class: "btn btn-secondary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <%= render 'books/list', user: @user, book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
       <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan=3></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= image_tag user.get_profile_image %>
            </td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <%= render 'books/list', user: @user, book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
       <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan=3></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <th>
              <%= link_to do %>
                <%= image_tag book.user.get_profile_image %>
              <% end %>
            </th>
            <th>
              <%= link_to book.title, book_path(book.id) %>
            </th>
            <th>
              <%= book.body %>
            </th>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>